spring.application.name=senior-app

server.port=8080


spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:3306}/seniorapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# MySQL 8+ kullanıyorsanız Dialect belirtmeye gerek yok ama kalsın dersen:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Ayarları
app.jwt.secret=CHANGE_ME_IN_PRODUCTION_use_a_long_random_secret_key_at_least_256_bits
app.jwt.expiration-ms=86400000

# CORS - Frontend Vite portu 5173 olarak kalmalı
app.cors.allowed-origins=http://localhost:5173

# Email Sunucu Ayarları
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seniorapp2test@gmail.com
spring.mail.password=grisjtaqbmjwyfiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GitHub OAuth Ayarları
github.client.id=${GITHUB_CLIENT_ID:}
github.internal.default-client-id=Ov23lidzjwQNEQ4tC4D0
github.internal.default-client-secret=ffccbf38b88fff9e57af098108cea9df6b16d9f9
# Callback URL 5173 (Frontend) üzerinden döner
github.redirect.uri=http://localhost:5173/auth/github/callback
github.client.secret=${GITHUB_CLIENT_SECRET:}